### ISSUE TITLE
macro expansion

### ISSUE THREAD

**Issue by yonik** [Heliosearch/heliosearch#10]
Being able to reference other request parameters is powerful (as can currently be done in localParams), but it would be nice to be able to do this at a higher level such that parameter substitution would work _anywhere_ in request parameters (i.e. in a query in lucene syntax, etc).

**Comment by yonik** [comment]
OK, the basics are in
- param substitution / macro expansion works on all request parameters (including parameter names!), and expansion is done at the same time defaults are applied (when the request reaches the right request handler).

Example:
q=field:[ ${low} TO ${high} ]
&low=10
&high=20

One can also specify defaults:
q=field:[ ${low:0} TO ${high:100} ]

Lots more to do to make this even more useful, but we've got a good start I think.

**Comment by arafalov** [comment]
So is competing with ElasticSearch's templates part of the goal?

**Comment by yonik** [comment]
Hmmm, interesting, I hadn't seen that (although I had run across mustache before).
This was more a natural extension of localParams parameter dereferencing.  I was planning on adding parameter dereferencing to the lucene query syntax, and was lamenting that stuff like this would need to be done for every query language.  Then it struck me that we could do it at a higher level (or lower, depending on how you see it) and have something that would work everywhere.

**Comment by arafalov** [comment]
An interesting comparison article is here:
http://blog.sematext.com/2014/04/29/parametrizing-queries-in-solr-and-elasticsearch/

Regards,
   Alex.

Personal website: http://www.outerthoughts.com/
Current project: http://www.solr-start.com/ - Accelerating your Solr
proficiency

**Comment by yonik** [comment]
Hmmm, so I guess we could do named templates in the future... (basically like request handlers today, but more dynamic).  That would be orthogonal to this macro expansion of course.
