### ISSUE TITLE
native code faceting for single-valued string fields

### ISSUE THREAD

**Issue by yonik** [Heliosearch/heliosearch#12]

**Comment by yonik** [comment]
It looks like this resulted in over 2x performance:
http://heliosearch.org/native-code-faceting/

**Comment by noblepaul** [comment]
It says the QPS went up by a factor of two. Any numbers on the response
times? Is it also halved?

On Mon, Jun 9, 2014 at 10:50 PM, Yonik Seeley notifications@github.com
wrote:

> It looks like this resulted in over 2x performance:
> http://heliosearch.org/native-code-faceting/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Heliosearch/heliosearch/issues/12#issuecomment-45517553
> .

## 

---

Noble Paul

**Comment by yonik** [comment]
Yep, response times were inversely proportional to QPS so it was redundant to report both.
For example on my macbook, the latency went from 173.7ms to 70.5ms
173/70.5 = 2.46 ... the same multiplication factor for QPS.
