### ISSUE TITLE
NPE using hs 0.06 and MoreLikeThisHandler with facets

### ISSUE THREAD

**Issue by mikeystix** [Heliosearch/heliosearch#17]
NPE using facets with the MoreLikeThisHandler produces the following trace.

java.lang.NullPointerException at

org.apache.solr.search.facet.SimpleFacets.addFacets(SimpleFacets.java:375)

at

org.apache.solr.handler.MoreLikeThisHandler.handleRequestBody(MoreLikeThisHandler.java:211)

at

org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)

at org.apache.solr.core.SolrCore.execute(SolrCore.java:1955) at

org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:769)

at

org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)

at

org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)

at

org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)

at

org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)

at

org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)

at

org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)

at

org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)

at

org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)

at

org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)

at

org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)

at

org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)

at

org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)

at

org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)

at

org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)

at

org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)

at org.eclipse.jetty.server.Server.handle(Server.java:368) at

org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)

at

org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)

at

org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:953)

at

org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1014)

at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:861) at

org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) at

org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)

at

org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)

at

org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)

at

org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)

at java.lang.Thread.run(Thread.java:744)

**Comment by yonik** [comment]
OK, I've committed a fix.
https://github.com/Heliosearch/heliosearch/commit/1eb99396c3def6b76fcbbe2695e3157b247bcbdd
