### ISSUE TITLE
How to use json.facet with  date ranges

### ISSUE THREAD

**Issue by kala725** [Heliosearch/heliosearch#30]
http://localhost:8983/solr/query?q=_:_&rows=0&json.facet={bydate:{range:{field:delivery_date,start:NOW/DAY-160DAYS,end:NOW/DAY%2B1DAY,gap:%2B7DAY}}}

I am getting hte following error while using date ranges althouhg it works fine with price ranges.

 "error":{
    "msg":"Expected ',' or '}': char=+,position=69 BEFORE='range:{field:delivery_date,start:NOW/DAY-160DAYS,end:NOW/DAY+' AFTER='1DAY,gap:+7DAY}}}'",
    "trace":"org.noggit.JSONParser$ParseException: Expected ',' or '}': char=+,position=69 BEFORE='range:{field:delivery_date,start:NOW/DAY-160DAYS,end:NOW/DAY+' AFTER='1DAY,gap:+7DAY}}}'\n\tat org.noggit.JSONParser.err(JSONParser.java:356)\n\tat org.noggit.JSONParser.nextEvent(JSONParser.java:958)\n\tat org.noggit.ObjectBuilder.getObject(ObjectBuilder.java:124)\n\tat org.noggit.ObjectBuilder.getVal(ObjectBuilder.java:57)\n\tat org.noggit.ObjectBuilder.getObject(ObjectBuilder.java:128)\n\tat org.noggit.ObjectBuilder.getVal(ObjectBuilder.java:57)\n\tat org.noggit.ObjectBuilder.getObject(ObjectBuilder.java:128)\n\tat org.noggit.ObjectBuilder.getVal(ObjectBuilder.java:57)\n\tat org.noggit.ObjectBuilder.getVal(ObjectBuilder.java:37)\n\tat org.noggit.ObjectBuilder.fromJSON(ObjectBuilder.java:33)\n\tat org.apache.solr.search.facet.FacetModule.getFacetRequest(FacetModule.java:48)\n\tat org.apache.solr.search.facet.FacetModule.doFacets(FacetModule.java:71)\n\tat org.apache.solr.handler.component.FacetComponent.process(FacetComponent.java:93)\n\tat org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:219)\n\tat org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)\n\tat org.apache.solr.core.SolrCore.execute(SolrCore.java:1955)\n\tat org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:777)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:418)\n\tat org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:368)\n\tat org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handleRequest(BlockingHttpConnection.java:53)\n\tat org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:942)\n\tat org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1004)\n\tat org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)\n\tat org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)\n\tat org.eclipse.jetty.server.BlockingHttpConnection.handle(BlockingHttpConnection.java:72)\n\tat org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:264)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)\n\tat java.lang.Thread.run(Thread.java:745)\n",
    "code":500}}

**Comment by yonik** [comment]
This is a parsing error at the JSON level...
Although we allow unquoted strings for simple strings (things that look
like identifiers), more complicated strings need single or double quotes.

So instead of
  start:NOW/DAY-160DAYS
try
  start:"NOW/DAY-160DAYS"

-Yonik

**Comment by kala725** [comment]
Thank you

**Comment by jmartelrv** [comment]
Hi,

I am haing the same problem and even y use doubles quoted it does not work (NOTE: I am using SOLR 5). My query:

http://xxxxxxx:8983/solr/pulsoTwitterTweets/select?json={query:%22_:_%22}&json.facet.category={range:{field:dtmFecha,start:%222015-07-01T00:00:00Z%22,end:%222015-08-01T00:00:00Z%22,gap:%22%2B7DAY%22}}

Response:

<response>
<lst name="responseHeader">
<int name="status">400</int>
<int name="QTime">1</int>
<lst name="params">
<str name="json.facet.category">
{range:{field:dtmFecha,start:"2015-07-01T00:00:00Z",end:"2015-08-01T00:00:00Z",gap:"+7DAY"}}
</str>
<str name="json">{query:"_:_"}</str>
</lst>
</lst>
<result name="response" numFound="5090287" start="0">...</result>
<lst name="error">
<str name="msg">
Unable to range facet on tried field of unexpected type:dtmFecha
</str>
<int name="code">400</int>
</lst>
</response>

THANKS,

JAIME
