### ISSUE TITLE
Seems like some filter does not applying to subfacets

### ISSUE THREAD

**Issue by argakon** [Heliosearch/heliosearch#33]
My index structure:
p_make - string
p_model - string, not all documents have this value
cost_num - float

I try to get average price of each model which have make = honda

Query:
select?q=_%3A_&fq=cost_num%3A%5B1+TO+10000000%5D+AND+p_make%3Ahonda&rows=0&wt=json&indent=true&json.facet={%22make%22:{%22terms%22:{%22field%22:%22p_make%22,%22limit%22:20,%22facet%22:{%22avg%22:%22avg%28cost_num%29%22,%22model%22:{%22terms%22:{%22field%22:%22p_model%22,%22limit%22:2,%22mincount%22:2,%22facet%22:{%22avg%22:%22avg%28cost_num%29%22}}}}}}}&facet=true&facet.pivot=p_make,p_model&facet.limit=2

And Solr Response is:
{
  "responseHeader":{
    "status":0,
    "QTime":25,
    "params":{
      "facet":"true",
      "indent":"true",
      "q":"_:_",
      "facet.limit":"2",
      "json.facet":"{\"make\":{\"terms\":{\"field\":\"p_make\",\"limit\":20,\"facet\":{\"avg\":\"avg(cost_num)\",\"model\":{\"terms\":{\"field\":\"p_model\",\"limit\":2,\"mincount\":2,\"facet\":{\"avg\":\"avg(cost_num)\"}}}}}}}",
      "wt":"json",
      "facet.pivot":"p_make,p_model",
      "fq":"cost_num:[1 TO 10000000] AND p_make:honda",
      "rows":"0"}},
  "response":{"numFound":47317,"start":0,"docs":[]
  },
  "facets":{
    "count":47317,
    "make":{
      "buckets":[{
          "val":"honda",
          "count":47317,
          "avg":13220.191009573726,
          "model":{
            "buckets":[{
                "val":"accord",
                "count":29442,
                "avg":5673.630663677739},
              {
                "val":"civic",
                "count":23621,
                "avg":5454.429787053893}]}}]}},
  "facet_counts":{
    "facet_pivot":{
      "p_make,p_model":[{
          "field":"p_make",
          "value":"honda",
          "count":47317,
          "pivot":[{
              "field":"p_model",
              "value":"accord",
              "count":11320},
            {
              "field":"p_model",
              "value":"civic",
              "count":10476}]}]}}}

As we can see... pivots model count different from json.facet model. Seems like filters not applying to subfacets(model), because sum of civic and accord count in json.facet larger than honda count. For 1-level facet is all right.

**Comment by yonik** [comment]
Hmmnm, thanks for the report. I'll try to reproduce in a smaller test case.

**Comment by yonik** [comment]
I have not been able to reproduce what you are seeing.
Is this heliosearch 0.08?  Is there anything special about your field types (I assume "string" is the standard type from the example schema.xml?)
Can you reproduce with a small example or testcase you can share?

See my attempts to reproduce (as a test case) at
https://github.com/Heliosearch/heliosearch/commit/fc0187c6b16a42fe071b7744ceb66aa3f8a43e06

**Comment by argakon** [comment]
Ok, i will try reproduce, but i write test on PHP, is that ok?
Yes, first of all i try heliosearch 0.08 and after that i build heliosearch from latest sources and problem remains.
Part of my schema.xml file:

field name="id" type="string" indexed="true" stored="true" required="true" multiValued="false" 
field name="p_make" type="string" indexed="true" stored="true"
field name="p_model" type="string" indexed="true" stored="true" 
field name="cost_num" type="tfloat" indexed="true" stored="true"

fieldType name="string" class="solr.StrField" sortMissingLast="true" 
fieldType name="tfloat" class="solr.TrieFloatField" precisionStep="8" positionIncrementGap="0"

**Comment by argakon** [comment]
So... i changed your test case and make patch. For simplify i removed avg stat and unnecessary params, add several prices(10000, 30000, 50000, 0) for filtering.
If we removing from fq +cost_f:[11000 TO 100000] test OK, if we change the range, set to [0 TO 100000] test OK, set to min value larger 10000(exclude results with price 10000 and 0) test FAILED.

I run test with command
ant -Dtestcase=TestJsonFacets clean test

Environment:
java version "1.7.0_71"
OpenJDK Runtime Environment (rhel-2.5.3.1.el6-x86_64 u71-b14)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Patch:
http://pastebin.com/hCqgHdVr

**Comment by yonik** [comment]
You forgot to adjust the counts to account for the price filter.  But after fixing that I do see the failure.
Working on a fix now... thank you for your efforts in reproducing this!

**Comment by argakon** [comment]
I'm sorry, i'm only know a little of java. You are welcome!

**Comment by yonik** [comment]
OK, should be fixed.  Thanks again!

Interesting tidbit for others following along... when debugging these issues, if you paste the complete JSON response into
http://www.freeformatter.com/json-formatter.html
it will even format the embedded facet.json (that appear in the header) nicely!
